### ISSUE TITLE
Lichess server doesn't reconnect when client IP changes

### ISSUE THREAD

**Issue by koedem** [ShailChoksi/lichess-bot#135] opened 2018-07-30 10:31 UTC
My internet provider changes my IP once a day which messes with the bot client. (I haven't observed problems when playing as a human though) I guess for that to not be a problem the client would need to send some keepalive signal and if it doesn't get returned start a new connection? Maybe worth noting that one can still send moves with the changed IP address but one doesn't get the response moves anymore. (even though by receiving the move, lichess should already learn the new IP)
Log:
"DEBUG:chess.engine:<PopenProcess at 0x7fe7c3118940 (pid=7960)> >> info depth 9 currmove f4g6 currmovenumber 22
DEBUG:chess.engine:<PopenProcess at 0x7fe7c3118940 (pid=7960)> >> info depth 9 score cp -194 nodes 140077506 nps 396496 time 353288 pv f1e1 c4c2 a3a7 d8b8 e1d1 c2h2 d1c1 b8b2 a2a4
DEBUG:chess.engine:<PopenProcess at 0x7fe7c3118940 (pid=7960)> >> bestmove f1e1
DEBUG:urllib3.connectionpool:Resetting dropped connection: lichess.org
DEBUG:urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/tPh8e45K/move/f1e1 HTTP/1.1" 200 None
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 currmove g8g7 currmovenumber 25
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 currmove h7h6 currmovenumber 26
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 currmove h7h5 currmovenumber 27
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 currmove h8g7 currmovenumber 28
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 currmove h8f6 currmovenumber 29
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 currmove h8e5 currmovenumber 30
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> info depth 8 score cp 10 nodes 233495743 nps 288036 time 810647 pv d7d6 c3d2 d8e6 e2e3 f4d5 d1c3 d5c3 d2c3
DEBUG:chess.engine:<PopenProcess at 0x7fe7c31136a0 (pid=9258)> >> bestmove d7d6
DEBUG:urllib3.connectionpool:Resetting dropped connection: lichess.org
DEBUG:urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/gBPk40zz/move/d7d6 HTTP/1.1" 200 None
"

These are the corresponding games, as you can see in both games the move did still get played just no response on the moves played by SF: https://lichess.org/tPh8e45K#98 https://lichess.org/gBPk40zz/black#9

**Comment by careless25** [comment] 2018-08-27 18:02
Just merged a possible fix for this. Can you re-test? https://github.com/careless25/lichess-bot/pull/133

**Comment by koedem** [comment] 2018-08-30 05:38
I pulled and refilled the config.yml file however it still doesn't seem to
reconnect. Is there anything else I should have done?
Will try with -v flag now to see if I can find out more. Worth noting that
it seems on disconnect I can't close the program with CTRL+C anymore which
previously worked, not sure if it's related. (maybe it died and the
terminal just didn't show that?!)

**Comment by gbtami** [comment] 2018-08-30 10:31
@careless25 #133 was not meant to address this issue at all. (It just suppress invalid traceback shit in case of game ended while BOT is thinking on next move.)
 
@koedem can you paste the console log lines you get with -v, please?

**Comment by koedem** [comment] 2018-09-01 14:35
Looking at it there doesn't seem to be anything of interest @gbtami 
The last line is a challenge getting declined, afterwards nothing. (i.e. it doesn't realize that it disconnected; which is not surprising, otherwise it would try to reconnect)

**Comment by gbtami** [comment] 2018-09-01 18:40
@koedem if I understand correctly your make_move() after "Resetting dropped connection" works OK on both games you presented in your first post. It uses api_post() which calls session.post() at the and. But game updates coming from get_game_stream() uses pure request.get() not session.get()
Try to change from
`return requests.get(url, headers=self.header, stream=True)`
to
`return self.session.get(url, headers=self.header, stream=True)`
at https://github.com/careless25/lichess-bot/blob/master/lichess.py#L87
(I'm not a network programming expert, so maybe what I suggest here is completely wrong.)

**Comment by koedem** [comment] 2018-09-01 20:42
That wouldn't solve the problem of disconnecting while being idle though, right? (which is not a huge problem, but it is a minor annoyance to have to restart the program every morning to reconnect)

**Comment by gbtami** [comment] 2018-09-01 21:06
I'm confused. From opening post log I see that lichess-bot is reconnected and sent your last engine move but after that it never get the opponent next move from the server and lost on time. My suggestion is an attempt to fix this.
I don't understand your latest comment at all. Why do you have to restart the program every morning if it's already reconnected. ("The last line is a challenge getting declined" means you are connected to the server, arn't you?)

**Comment by koedem** [comment] 2018-09-01 21:18
The last line being "Challenge declined ..." means it was connected until
recently. However then it is not online anymore and doesn't receive
challenges. (that being the last line means it never actually realized that
it's not online anymore otherwise it would spit out some error messages)
This all is in the scenario where the bot is NOT playing a game while the
IP change happens.

**Comment by koedem** [comment] 2018-09-08 02:48
It does not seem to work, it disconnected again, without me seeing any reaction on the client side. Not sure who to move it was when the disconnect happened though. Maybe it was Stockfishs turn so the client to this date is still waiting to receive the move. Without a general automatic reconnect that problem probably won't go away.

**Comment by koedem** [comment] 2018-09-11 21:19
@gbtami To repeat the question I asked in the issue, couldn't one have some kind of keepalive signal? Send a ping to lichess through the connection once a minute, and if one doesn't get a response, drop the old one and create a fresh connection.

**Comment by ddugovic** [comment] 2018-10-18 09:50
When Lichess restarts, the following is logged (date/time prefix is prepended by the `systemd` logger):

```
Oct 18 02:34:01 vps178028 python3[8902]: INFO:backoff:Backing off watch_control_stream(...) for 0.6s (requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)))
Oct 18 02:34:20 vps178028 python3[8902]: ERROR:backoff:Giving up watch_control_stream(...) after 2 tries (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Oct 18 02:34:20 vps178028 python3[8902]: Process Process-2:
Oct 18 02:34:20 vps178028 python3[8902]: Traceback (most recent call last):
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
Oct 18 02:34:20 vps178028 python3[8902]:     chunked=chunked)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
Oct 18 02:34:20 vps178028 python3[8902]:     self._validate_conn(conn)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
Oct 18 02:34:20 vps178028 python3[8902]:     conn.connect()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
Oct 18 02:34:20 vps178028 python3[8902]:     ssl_context=context)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
Oct 18 02:34:20 vps178028 python3[8902]:     return context.wrap_socket(sock, server_hostname=server_hostname)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
Oct 18 02:34:20 vps178028 python3[8902]:     _context=self, _session=session)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 814, in __init__
Oct 18 02:34:20 vps178028 python3[8902]:     self.do_handshake()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
Oct 18 02:34:20 vps178028 python3[8902]:     self._sslobj.do_handshake()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
Oct 18 02:34:20 vps178028 python3[8902]:     self._sslobj.do_handshake()
Oct 18 02:34:20 vps178028 python3[8902]: ConnectionResetError: [Errno 104] Connection reset by peer
Oct 18 02:34:20 vps178028 python3[8902]: During handling of the above exception, another exception occurred:
Oct 18 02:34:20 vps178028 python3[8902]: Traceback (most recent call last):
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
Oct 18 02:34:20 vps178028 python3[8902]:     timeout=timeout
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
Oct 18 02:34:20 vps178028 python3[8902]:     _stacktrace=sys.exc_info()[2])
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
Oct 18 02:34:20 vps178028 python3[8902]:     raise six.reraise(type(error), error, _stacktrace)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
Oct 18 02:34:20 vps178028 python3[8902]:     raise value.with_traceback(tb)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
Oct 18 02:34:20 vps178028 python3[8902]:     chunked=chunked)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
Oct 18 02:34:20 vps178028 python3[8902]:     self._validate_conn(conn)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
Oct 18 02:34:20 vps178028 python3[8902]:     conn.connect()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
Oct 18 02:34:20 vps178028 python3[8902]:     ssl_context=context)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
Oct 18 02:34:20 vps178028 python3[8902]:     return context.wrap_socket(sock, server_hostname=server_hostname)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
Oct 18 02:34:20 vps178028 python3[8902]:     _context=self, _session=session)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 814, in __init__
Oct 18 02:34:20 vps178028 python3[8902]:     self.do_handshake()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
Oct 18 02:34:20 vps178028 python3[8902]:     self._sslobj.do_handshake()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
Oct 18 02:34:20 vps178028 python3[8902]:     self._sslobj.do_handshake()
Oct 18 02:34:20 vps178028 python3[8902]: urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Oct 18 02:34:20 vps178028 python3[8902]: During handling of the above exception, another exception occurred:
Oct 18 02:34:20 vps178028 python3[8902]: Traceback (most recent call last):
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Oct 18 02:34:20 vps178028 python3[8902]:     self.run()
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
Oct 18 02:34:20 vps178028 python3[8902]:     self._target(*self._args, **self._kwargs)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/home/turing/.local/lib/python3.6/site-packages/backoff/_sync.py", line 99, in retry
Oct 18 02:34:20 vps178028 python3[8902]:     ret = target(*args, **kwargs)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/home/turing/lichess-bot/lichess-bot.py", line 42, in watch_control_stream
Oct 18 02:34:20 vps178028 python3[8902]:     for evnt in li.get_event_stream().iter_lines():
Oct 18 02:34:20 vps178028 python3[8902]:   File "/home/turing/lichess-bot/lichess.py", line 83, in get_event_stream
Oct 18 02:34:20 vps178028 python3[8902]:     return requests.get(url, headers=self.header, stream=True)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
Oct 18 02:34:20 vps178028 python3[8902]:     return request('get', url, params=params, **kwargs)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
Oct 18 02:34:20 vps178028 python3[8902]:     return session.request(method=method, url=url, **kwargs)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
Oct 18 02:34:20 vps178028 python3[8902]:     resp = self.send(prep, **send_kwargs)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
Oct 18 02:34:20 vps178028 python3[8902]:     r = adapter.send(request, **kwargs)
Oct 18 02:34:20 vps178028 python3[8902]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
Oct 18 02:34:20 vps178028 python3[8902]:     raise ConnectionError(err, request=request)
Oct 18 02:34:20 vps178028 python3[8902]: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by careless25** [comment] 2018-12-10 10:44
With the latest changes and if you are running the BOT as a service, this should be solved. Can you update and give it a try?

**Comment by zgtm** [comment] 2021-02-15 12:08
Unfortunately the bot is still unreactive from the moment on the IP address of the bot changes.

There seem to be no hints in the log, but the Lichess-API and the bot seem not to be able to talk to eachother anymore:

![Screenshot_20210215_125951](https://user-images.githubusercontent.com/17168083/107944423-5d857a80-6f8e-11eb-84a2-fb818cda3f31.png)

Furthermore, the bot can then no longer be terminated using Ctrl+C, it says `Recieved SIGINT. Terminating client.` but keeps on running until kill the processes using `kill`.

> With the latest changes and if you are running the BOT as a service, this should be solved. Can you update and give it a try?

What do you mean with “as a service”? Does it make a difference?

Any way I can help finding the cause of this bug?

**Comment by MarkZH** [comment] 2022-08-01 11:44
Copying my post from #222.

Perhaps some features added lately might help resolve this (if anyone is still watching this old issue).

Before the matchmaking feature was added, which lets bots issue challenges instead of waiting for them, lichess-bot passively listened for messages from lichess.org. Maybe, once lichess resets itself, it simply stops sending messages to old connections. Now, with matchmaking sending messages to lichess, this should keep the connection active, or cause an error in communication that would cause lichess-bot to establish a new connection.

Can the reporters here test the latest version of lichess-bot with matchmaking enabled?

**Closed** 2022-08-07 03:36 UTC
