### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by sander-NULL** [ShailChoksi/lichess-bot#381] opened 2021-08-03 19:39 UTC
After the bot runs smoothly without issues for a day accepting games doesn't function anymore. As the opponent one would see the circle on lichess going round and round but the actual game never starts. The bot also appears online and one can still terminate it properly via CTRL + C.

**Comment by MarkZH** [comment] 2021-08-04 01:53
Are you talking about starting a rematch against a bot? If so, this is the same problem reported at #379 and #376.

The problem seems to have been [fixed on the lichess site](https://github.com/ornicar/lila/commit/47e438f19b299a3512ecf303bb7317d8ab810375). Please check to see if the problem is solved.

**Comment by sander-NULL** [comment] 2021-08-04 09:30
No, this is not about rematches. At least it happened to me without playing any matches before against the bot.
Though what could have happened is that someone else tried to play a rematch before and the bot crashed because of this. But I don't see a way to check this. I'll see if that error occurs again and if not that might have been the reason then.

**Comment by MarkZH** [comment] 2021-08-04 09:41
What's the challenge concurrency setting in your `config.yml`?

**Comment by sander-NULL** [comment] 2021-08-04 09:57
I have set the concurrency to 1.

**Comment by MarkZH** [comment] 2021-08-04 10:02
It sounds like someone tried to start a rematch game against your bot, but a bug in the lichess code never started the game, leaving lichess-bot with a game stuck in the queue and not allowing any more games to start. That problem should be fixed now. Let me know if your bot stops accepting games again.

**Comment by ornicar** [comment] 2021-08-08 08:52
It was fixed on Lichess side

**Closed by ornicar** 2021-08-08 08:52 UTC
