### ISSUE TITLE
Repeated moves (not in correspondence)

### ISSUE THREAD

**Issue by josiahmanson** [ShailChoksi/lichess-bot#214] opened 2020-08-09 10:32 UTC
I'm getting repeated moves that are crashing my bot. I saw a bug report about repeated moves, but mine is different in that it is not a correspondence game.

Here is a transcript of a UCI with the problem where you can see that f3f7 is repeated. This has happened to me on several occasions.

```
uci
setoption name Move Overhead value 100
setoption name Ponder value true
setoption name Threads value 6
setoption name Hash value 256
isready
setoption name UCI_Variant value chess
setoption name UCI_Chess960 value false
isready
position startpos
position startpos moves e2e4
go movetime 10000
position startpos moves e2e4 a7a5 f1c4
go wtime 598940 btime 598000 winc 0 binc 0
position startpos moves e2e4 a7a5 f1c4 c7c5 d1f3
go wtime 598230 btime 597930 winc 0 binc 0
position startpos moves e2e4 a7a5 f1c4 c7c5 d1f3 e7e5 f3f7 f3f7
go wtime 594780 btime 599860 winc 0 binc 0
```

I can make my bot tolerant to such repeats, but I feel that I should be able to expect valid UCI commands.

**Comment by astrokrautt** [comment] 2020-09-12 03:30
I can confirm encountering this as well. I've modified my engine to work around it for the moment.

**Comment by MarkZH** [comment] 2020-09-13 18:16
Can someone try out my pull request to see if it fixes the problem?

**Comment by Tearth** [comment] 2020-09-16 15:32
It happens in nearly every game, so I can definitely confirm this. My bot plays bullets, blitzs and rapids. Example:
```
position startpos moves e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 f8c5 c2c3 f6e4 d1e2 c5f2 g1h1 d7d5 c3c4 f2b6 c4d5 d8d5 b5c4 c6d4 c4d5 d4e2 d5e4 f7f5 e4d5 e5e4 f3g5 h7h6 g5f7 h8f8 d2d3 e2c1 f1c1 c7c6 f7d6 e8d7 d6c8 b6d4 c8a7 c6d5 c1c7 d7e6 c7b7 a8a7 b7a7 d4a7 b1c3 f8b8 d3e4 f5e4 a1d1 b8b2 c3d5 e4e3 d5f4 e6f5 g2g3 g7g5 f4h3 b2a2 h3g1 f5e4 d1e1 g5g4 g1e2 e4f3 e2c1 a2d2 c1b3 d2f2 e1d1 e3e2 b3d2 f3e3 d2c4 e3e4 c4d2 e4d3 d1b1 d3d2 h2h3 f2f1 h1g2 f1b1 h3g4 e2e1q g2f3 e1e2 f3f4 b1f1 b1f1
```

**Comment by MarkZH** [comment] 2020-09-16 16:39
If my pull request is not a satisfactory solution and soneine else wants to work on this, here's the problem:

When the winning (or possibly just game ending) move is made in a game,
lichess sends two JSON packets for that move. For example, here are the
last JSON packets received (gathered by adding `logger.info(str(upd))`
after line 208 in lichess-bot.py):

    {'type': 'gameState',
     'moves': 'b2b3 e7e5 a2a3 f8c5 h2h4 d8f6 e2e4',
     'wtime': 299800,
     'btime': 295210,
     'winc': 0,
     'binc': 0,
     'wdraw': False,
     'bdraw': False,
     'status': 'started'}

    {'type': 'gameState',
     'moves': 'b2b3 e7e5 a2a3 f8c5 h2h4 d8f6 e2e4 f6f2',
     'wtime': 299800,
     'btime': 293610,
     'winc': 0,
     'binc': 0,
     'wdraw': False,
     'bdraw': False,
     'status': 'mate'}

    {'type': 'gameState',
     'moves': 'b2b3 e7e5 a2a3 f8c5 h2h4 d8f6 e2e4 f6f2',
     'wtime': 299800,
     'btime': 293610,
     'winc': 0,
     'binc': 0,
     'wdraw': False,
     'bdraw': False,
     'status': 'mate',
     'winner': 'black'}

The first JSON packet is the last midgame move (notice that the `status`
is `started`.

The second JSON packet contains the game-winning move and the status has
changed to `mate`.

The third JSON packet only has the addition of `'winner': 'black'`. More
importantly, they both contain the same move lists, so duplicate move
are added when `board = update_board(board, moves[-1])` (line 215) is
called.

**Comment by MarkZH** [comment] 2020-09-16 16:49
Also, this is issue is a duplicate of #202.

**Comment by Tearth** [comment] 2020-09-16 17:47
I will try your fix and let you know about the results.

**Comment by Tearth** [comment] 2020-09-17 15:50
Looks like it's working like a charm - hopefully, your PR will be accepted soon (unless this repo is dead, looking at the activity of owners here).

**Comment by ShailChoksi** [comment] 2020-09-17 15:53
I will take a look soon. Sorry have been busy and haven't been able to keep up with this

**Comment by Tearth** [comment] 2020-09-17 15:56
No problem, I understand this

**Comment by MarkZH** [comment] 2020-09-17 18:26
Another solution might be to replace line 215 `board = update_board(board, moves[-1])` with `board = setup_board(game)`. That is, recreate the board from scratch on every move using the full move list. If lichess-bot ever wants to support move takebacks in games against bots, this might be better.

**Closed** 2020-09-22 10:22 UTC
