### ISSUE TITLE
No priority in correspondence games

### ISSUE THREAD

**Issue by OIVAS7572** [ShailChoksi/lichess-bot#339] opened 2021-05-20 14:31 UTC
Problem is happening when in these conditions :
* One day correspondence games.
* 50+ correspondence games at a time.

When bot playing large number of correspondence games at a time, Bot is not giving any priority to low time correspondence games. These leads to Timeout in a large number of correspondence games. It will lead to get message about restrictions from Lichess.
 Can anybody solve this problem. Please take it serious problem

**Comment by MarkZH** [comment] 2021-05-20 15:45
What settings do you have in the `correspondence` and `concurrency` sections of your `config.yml`?

**Comment by OIVAS7572** [comment] 2021-05-20 16:40
I found this problem after restarting bot.

concurrency: 1
correspondence:  
move_time: 60      
checkin_period: 1200  (also tryed 2 hour and 5 mins)
disconnect_time: 5 (also tryed 10sec ) 
ponder: false

**Comment by nkoppel** [comment] 2021-05-20 19:24
I can confirm that there is not system for prioritizing daily games that are low on time. Even so, it seems strange that daily games are timing out even with 50+, as the end of every game should the bot to check all correspondence games and to reject all challenges until it is has checked every game.

@OIVAS7572 Could you send over the output of the bot when it is failing to move in daily games?

**Comment by OIVAS7572** [comment] 2021-05-21 01:57
@nkoppel
I didn't found any error in logs.
Did you need verbose logs.
Or small logs

**Comment by OIVAS7572** [comment] 2021-05-21 02:09
2021-05-21T02:06:43.570248+00:00 app[worker.1]: 2021-05-21 02:06:43,570: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:06:44.040475+00:00 app[worker.1]: 2021-05-21 02:06:44,040: [94m+++ https://lichess.org/cVxiNpTe/black Correspondence vs BOT Official_bot(1395?)[0m
2021-05-21T02:06:50.683185+00:00 app[worker.1]: 2021-05-21 02:06:50,683: [94m--- Disconnecting from https://lichess.org/cVxiNpTe/black[0m
2021-05-21T02:06:50.684963+00:00 app[worker.1]: 2021-05-21 02:06:50,684: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:06:50.685197+00:00 app[worker.1]: 2021-05-21 02:06:50,685: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:06:51.139435+00:00 app[worker.1]: 2021-05-21 02:06:51,139: [94m+++ https://lichess.org/HC3QHm3g/black Correspondence vs MGCA2009(1635)[0m
2021-05-21T02:06:57.806171+00:00 app[worker.1]: 2021-05-21 02:06:57,805: [94m--- Disconnecting from https://lichess.org/HC3QHm3g/black[0m
2021-05-21T02:06:57.807923+00:00 app[worker.1]: 2021-05-21 02:06:57,807: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:06:57.808227+00:00 app[worker.1]: 2021-05-21 02:06:57,808: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:06:58.247194+00:00 app[worker.1]: 2021-05-21 02:06:58,246: [94m+++ https://lichess.org/1p7LWnq1/black Correspondence vs harithasunil(1470?)[0m
2021-05-21T02:07:04.922272+00:00 app[worker.1]: 2021-05-21 02:07:04,922: [94m--- Disconnecting from https://lichess.org/1p7LWnq1/black[0m
2021-05-21T02:07:04.924133+00:00 app[worker.1]: 2021-05-21 02:07:04,924: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:04.924417+00:00 app[worker.1]: 2021-05-21 02:07:04,924: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:05.456309+00:00 app[worker.1]: 2021-05-21 02:07:05,456: [94m+++ https://lichess.org/GG9yQGBE/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:11.056577+00:00 app[worker.1]: 2021-05-21 02:07:11,056: [94m--- Disconnecting from https://lichess.org/GG9yQGBE/black[0m
2021-05-21T02:07:11.058751+00:00 app[worker.1]: 2021-05-21 02:07:11,058: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:11.062541+00:00 app[worker.1]: 2021-05-21 02:07:11,062: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:11.537073+00:00 app[worker.1]: 2021-05-21 02:07:11,536: [94m+++ https://lichess.org/iBT99QpN/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:18.186753+00:00 app[worker.1]: 2021-05-21 02:07:18,186: [94m--- Disconnecting from https://lichess.org/iBT99QpN/black[0m
2021-05-21T02:07:18.188622+00:00 app[worker.1]: 2021-05-21 02:07:18,188: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:18.188964+00:00 app[worker.1]: 2021-05-21 02:07:18,188: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:18.828224+00:00 app[worker.1]: 2021-05-21 02:07:18,827: [94m+++ https://lichess.org/DsP8SVnM/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:25.315653+00:00 app[worker.1]: 2021-05-21 02:07:25,315: [94m--- Disconnecting from https://lichess.org/DsP8SVnM/black[0m
2021-05-21T02:07:25.317602+00:00 app[worker.1]: 2021-05-21 02:07:25,317: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:25.317899+00:00 app[worker.1]: 2021-05-21 02:07:25,317: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:25.813591+00:00 app[worker.1]: 2021-05-21 02:07:25,813: [94m+++ https://lichess.org/ncThp349/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:32.428897+00:00 app[worker.1]: 2021-05-21 02:07:32,428: [94m--- Disconnecting from https://lichess.org/ncThp349/black[0m
2021-05-21T02:07:32.431200+00:00 app[worker.1]: 2021-05-21 02:07:32,431: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:32.431612+00:00 app[worker.1]: 2021-05-21 02:07:32,431: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:33.002140+00:00 app[worker.1]: 2021-05-21 02:07:32,999: [94m+++ https://lichess.org/JhUhrG8B/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:39.558122+00:00 app[worker.1]: 2021-05-21 02:07:39,557: [94m--- Disconnecting from https://lichess.org/JhUhrG8B/black[0m
2021-05-21T02:07:39.559973+00:00 app[worker.1]: 2021-05-21 02:07:39,559: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:39.560290+00:00 app[worker.1]: 2021-05-21 02:07:39,560: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:40.117950+00:00 app[worker.1]: 2021-05-21 02:07:40,117: [94m+++ https://lichess.org/2k8luSJz/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:46.685959+00:00 app[worker.1]: 2021-05-21 02:07:46,685: [94m--- Disconnecting from https://lichess.org/2k8luSJz/black[0m
2021-05-21T02:07:46.688386+00:00 app[worker.1]: 2021-05-21 02:07:46,688: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:46.688735+00:00 app[worker.1]: 2021-05-21 02:07:46,688: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:47.231877+00:00 app[worker.1]: 2021-05-21 02:07:47,231: [94m+++ https://lichess.org/KbP2MXni/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:52.836261+00:00 app[worker.1]: 2021-05-21 02:07:52,836: [94m--- Disconnecting from https://lichess.org/KbP2MXni/black[0m
2021-05-21T02:07:52.838553+00:00 app[worker.1]: 2021-05-21 02:07:52,838: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:52.840688+00:00 app[worker.1]: 2021-05-21 02:07:52,840: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:07:53.342469+00:00 app[worker.1]: 2021-05-21 02:07:53,342: [94m+++ https://lichess.org/eJvoU9xj/black Correspondence vs Anu_india(1315?)[0m
2021-05-21T02:07:59.955845+00:00 app[worker.1]: 2021-05-21 02:07:59,955: [94m--- Disconnecting from https://lichess.org/eJvoU9xj/black[0m
2021-05-21T02:07:59.957891+00:00 app[worker.1]: 2021-05-21 02:07:59,957: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:07:59.958167+00:00 app[worker.1]: 2021-05-21 02:07:59,958: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:08:00.497369+00:00 app[worker.1]: 2021-05-21 02:08:00,497: [94m+++ https://lichess.org/Pe3fUTjc/white Correspondence vs uwrao(1500?)[0m
2021-05-21T02:08:07.074884+00:00 app[worker.1]: 2021-05-21 02:08:07,074: [94m--- Disconnecting from https://lichess.org/Pe3fUTjc/white[0m
2021-05-21T02:08:07.078053+00:00 app[worker.1]: 2021-05-21 02:08:07,076: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0m
2021-05-21T02:08:07.078055+00:00 app[worker.1]: 2021-05-21 02:08:07,077: [94m--- Process Used. Total Queued: 0. Total Used: 1[0m
2021-05-21T02:08:07.594347+00:00 app[worker.1]: 2021-05-21 02:08:07,593: [94m+++ https://lichess.org/squf9RM3/black Correspondence vs Heiwhei45(1500?)[0m
2021-05-21T02:08:14.191320+00:00 app[worker.1]: 2021-05-21 02:08:14,191: [94m--- Disconnecting from https://lichess.org/squf9RM3/black[0m
2021-05-21T02:08:14.195609+00:00 app[worker.1]: 2021-05-21 02:08:14,195: [94m+++ Process Free. Total Queued: 0. Total Used: 0[0

**Comment by nkoppel** [comment] 2021-05-21 04:03
Ok, I think I've found the issue. When there are more correspondence games than available threads and the bot initially connects to the lichess servers, the main thread receives each game id in a "gameStart" event. Issue being, gameStart events always try to start a thread, and since some of the games cannot have a thread started for them, the bot forgets about them and will never check for moves.

**Comment by OIVAS7572** [comment] 2021-05-21 04:28
Is there any solution
Did I want to increase threads in config.yml

**Comment by nkoppel** [comment] 2021-05-21 12:16
Increasing the number of threads may fix things in the short term, but it will cause a number of other problems, such as greatly reducing the amount of computation each thread can use. I recommend only restarting when it has few active games so that each one can get a thread assigned to them. I'll open a pr momentarily.

**Comment by nkoppel** [comment] 2021-05-21 12:30
The pr: #341

**Comment by OIVAS7572** [comment] 2021-05-21 13:50
Thanks
I will close this soon.

**Comment by OIVAS7572** [comment] 2021-05-22 05:45
@nkoppel 
This problem solved in my one bot but my other bot's not solved.
settings are :-
correspondence:
move_time: 30 (also tried 60 sec)
checkin_period: 1200 (also tryed 1 hour)
disconnect_time: 5
ponder: false
concurrency: 1
[Logs](https://gist.github.com/OIVAS7572/ffb8d33eb3d52d6ad51a459ae3ef827c)

Thanks

**Comment by OIVAS7572** [comment] 2021-05-22 06:53
How many correspondence games this bot can play with concorrency: 1

**Comment by MarkZH** [comment] 2021-05-22 07:11
Does this problem only happen when you restart lichess-bot? Or does it also happen without restarting?

**Comment by OIVAS7572** [comment] 2021-05-22 07:30
It is happening without restart
I restarted when I saw this problem

**Comment by MarkZH** [comment] 2021-05-22 07:34
In the last log you posted, were there no messages from 2021-05-22 04:18 to 2021-05-22 05:30? Or were those deleted to make the log shorter?

**Comment by OIVAS7572** [comment] 2021-05-22 07:35
that logs are taken at different time

**Comment by OIVAS7572** [comment] 2021-05-22 07:48
sorry I didn't add the last commits of [pr](https://github.com/ShailChoksi/lichess-bot/pull/341).
sometimes it will solve

**Comment by nkoppel** [comment] 2021-05-23 00:45
The current version of the pr does not check in on correspondence games until checkin_period seconds after the bot starts up. Please try waiting for 20 minutes after the bot starts and see if it connects to the correspondence games then.

**Closed** 2021-05-23 14:54 UTC

**Comment by OIVAS7572** [comment] 2021-05-23 14:55
@nkoppel
How many correspondence games it can play ?
Thanks for your Hardwork.

**Comment by nkoppel** [comment] 2021-05-23 16:29
@OIVAS7572 
With #342, it can handle upwards of 500 correspondence games per thread with low risk of timing out on any of them and without blocking incoming challenges for more than a couple of minutes.

**Comment by OIVAS7572** [comment] 2021-05-25 07:11
@nkoppel 
Ok
Thank you
