### ISSUE TITLE
TypeError: play() got an unexpected keyword argument 'draw_offered'

### ISSUE THREAD

**Issue by theoden8** [ShailChoksi/lichess-bot#395] opened 2021-10-01 01:34 UTC
When my bot starts a new game, I see the following error:

```
2021-10-01 04:24:28,734:   Using selector: EpollSelector
2021-10-01 04:24:28,735:   Using PollingChildWatcher
2021-10-01 04:24:28,741:   <UciProtocol (pid=1256946)>: Connection made
2021-10-01 04:24:28,742:   <UciProtocol (pid=1256946)>: << uci
2021-10-01 04:24:28,743:   <UciProtocol (pid=1256946)>: >> id name dummy_chess
2021-10-01 04:24:28,743:   <UciProtocol (pid=1256946)>: >> id author $USER
2021-10-01 04:24:28,743:   <UciProtocol (pid=1256946)>: >> option name Ponder type check default false
2021-10-01 04:24:28,744:   <UciProtocol (pid=1256946)>: >> option name UCI_Chess960 type check default false
2021-10-01 04:24:28,744:   <UciProtocol (pid=1256946)>: >> option name Hash type spin default 64 min 4 max 4096
2021-10-01 04:24:28,744:   <UciProtocol (pid=1256946)>: >> option name UCI_Variant type combo default chess var chess var crazyhouse
2021-10-01 04:24:28,744:   <UciProtocol (pid=1256946)>: >> uciok
2021-10-01 04:24:28,745:   <UciProtocol (pid=1256946)>: << setoption name Hash value 1024
2021-10-01 04:24:28,745:   +++ https://lichess.org/ ...
2021-10-01 04:24:28,745:   
2021-10-01 04:24:28,745:   move: 1
2021-10-01 04:24:28,745:   Searching for time 10000
2021-10-01 04:24:28,746:   Backing off play_game(...) for 1.3s (TypeError: play() got an unexpected keyword argument 'draw_offered')
2021-10-01 04:24:30,056:   Starting new HTTPS connection (1): lichess.org:443
2021-10-01 04:24:30,253:   https://lichess.org:443 "GET /api/bot/game/stream/... HTTP/1.1" 200 None
```

After some time the game is then aborted. How would I go about finding the cause of this?

**Comment by MarkZH** [comment] 2021-10-01 04:06
You probably need to upgrade the python-chess library. Run `python -m pip install -r requirements.txt` and see if that fixes it.

**Comment by theoden8** [comment] 2021-10-01 23:38
Thank you, it appears to have been the cause.

**Comment by MarkZH** [comment] 2021-10-02 01:02
Great! If the problem is fixed, you can close this issue.

**Closed** 2021-10-02 14:21 UTC
