### ISSUE TITLE
Low depth and nps in first move right after book move

### ISSUE THREAD

**Issue by iamhajemi** [ShailChoksi/lichess-bot#562] opened 2022-09-07 07:35 UTC
When engine starts think after book move it almost doesnt think. it making move immediately with 1 depth.

**Comment by MarkZH** [comment] 2022-09-07 10:14
Please run lichess-bot with `-v` for verbose logging and `-l` to save the log to a file like this: `python lichess-bot.py -v -l log.txt`

After a game that shows this problem, post the entire log here. Also, please post your configuration file (usually `config.yml`) after removing the token at the top of the file.

Both of these should help us figure out the problem.

**Comment by iamhajemi** [comment] 2022-09-07 16:10
> 

I set book depth to 12 so engine starts think after move 12. There is 6 game my bot played. Look for 13th moves. Almost each time engine doesnt think and playing in 1 depth and making blunder.
[log.txt](https://github.com/ShailChoksi/lichess-bot/files/9507856/log.txt)
[config.yml.txt](https://github.com/ShailChoksi/lichess-bot/files/9507866/config.yml.txt)

**Comment by AttackingOrDefending** [comment] 2022-09-07 17:43
Seems like a Stockfish bug because I could reproduce it by just running stockfish, without lichess-bot.
Running the same commands:
![1](https://user-images.githubusercontent.com/40605232/188943742-1635ddb2-4d38-4346-b573-5f4012eb9de8.jpg)
Only the necessary commands:
![2](https://user-images.githubusercontent.com/40605232/188943762-2e8b51b3-5a80-4f70-8df6-3caf30aa5e8b.jpg)
Only the necessary commands and then using setoption:
![3](https://user-images.githubusercontent.com/40605232/188943804-b30baa1a-2372-46e4-ac5d-f14be8cc7576.jpg)

**Comment by iamhajemi** [comment] 2022-09-07 18:04
> Seems like a Stockfish bug because I could reproduce it by just running stockfish, without `lichess-bot`.
> 
> Running the same commands (with an older version of SF, it only calculated up to depth 1 not 4, although 4 is still low): ![1](https://user-images.githubusercontent.com/40605232/188943742-1635ddb2-4d38-4346-b573-5f4012eb9de8.jpg) Only the necessary commands: ![2](https://user-images.githubusercontent.com/40605232/188943762-2e8b51b3-5a80-4f70-8df6-3caf30aa5e8b.jpg) Only the necessary commands and then using setoption: ![3](https://user-images.githubusercontent.com/40605232/188943804-b30baa1a-2372-46e4-ac5d-f14be8cc7576.jpg)
> 
> Also, did you compile the SF that you used because there is no version from the 6th of September (`060922`)? There is only `070922` and `290822`.

yes I compiled it myself with ubuntu

**Comment by AttackingOrDefending** [comment] 2022-09-08 05:44
> I tried windows there is no problem.

It also happens on windows because I tried this on windows and still had the same problem.

**Comment by MarkZH** [comment] 2022-09-17 10:05
Is this a stockfish issue?

**Comment by AttackingOrDefending** [comment] 2022-09-17 10:26
Seems like it. You can try it out by typing these commands:
```
uci
setoption name Move Overhead value 900
setoption name Ponder value true
ucinewgame
isready
position startpos moves e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 f6e4 d2d4 e4d6 b5c6 d7c6 d4e5 d6f5 d1d8 e8d8 b1c3 c8d7 h2h3 b7b6 g2g4 f5e7 f3g5 d8e8 f2f4
go wtime 29760 btime 25791 winc 0 binc 0
```

It seems to be happening even with NNUE disabled.
With NNUE:
![4](https://user-images.githubusercontent.com/40605232/190852166-66d96f88-3306-4cb2-a527-35ae39dfae13.jpg)
Without NNUE:
![5](https://user-images.githubusercontent.com/40605232/190852175-1da76827-934e-44b7-9b27-4c1b75c60ee7.jpg)

**Comment by MarkZH** [comment] 2022-09-17 10:59
This might be a relevant issue that could use some input from here: https://github.com/official-stockfish/Stockfish/issues/4000

**Comment by Matthies** [comment] 2022-10-09 10:17
1. https://github.com/official-stockfish/Stockfish/issues/4000 is not related here, this issue is about movestogo time control.
2. Your Move Overhead value of 900 is far too big. 900 means that it will take **0.9 seconds for every move** to be transfered between engine and gui. Stockfish assumes that a **game will have at least 50 moves** and **your game has 30 seconds** without any increment. So what do you expect from Stockfish other than moving immediately.
So with a lower Move Overhead you should be fine. Leave it to default of 10 and only increase it if you really see time forfeits.

**Comment by AttackingOrDefending** [comment] 2022-10-15 08:07
@iamhajemi Did you try lowering the Move Overhead as suggested above?

**Comment by MarkZH** [comment] 2022-11-07 05:58
I'm closing this bug since it doesn't seem related to lichess-bot. Please reopen if there is still a problem.

**Closed by MarkZH** 2022-11-07 05:58 UTC
